name: Deploy

on:
  workflow_call:
    inputs:
      gh-environment:
        required: true
        type: string
      task-definition:
        required: true
        type: string
      task-definition-family:
        required: true
        type: string
      task-execution-role:
        required: true
        type: string
      container-name:
        required: true
        type: string
      near-wallet-environment:
        required: true
        type: string
      aws-environment:
        required: true
        type: string
      aws-logs-group:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      node-url:
        required: false
        type: string
      wallet-url:
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ASSUMED_ROLE }}
          aws-region: ${{ inputs.aws-region }}
          # need to add sts:TagSession to role
          role-skip-session-tagging: true
          role-duration-seconds: 1200

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set docker image name
        id: image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "::set-output name=name::$REGISTRY/$REPOSITORY:$IMAGE_TAG"

      - uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: /tmp

      - run: docker load -i /tmp/image.tar
      - run: docker tag placeholder ${{ steps.image.outputs.name }}

      - name: Render ECS task definition
        id: render-task-def
        uses: bluwy/substitute-string-action@v1
        with:
          _input-file: ${{ inputs.task-definition }}
          _output-file: task-definition.json
          _format-key: '{{key}}'
          ContainerImage: ${{ steps.image.outputs.name }}
          AwsRegion: ${{ inputs.aws-region }}
          TaskDefinitionFamily: ${{ inputs.task-definition-family }}
          TaskExecutionRole: ${{ inputs.task-execution-role }}
          ContainerName: ${{ inputs.container-name }}
          Environment: ${{ inputs.aws-environment }}
          NearWalletEnvironment: ${{ inputs.near-wallet-environment }}
          AwsLogsGroup: ${{ inputs.aws-logs-group }}

      # - name: Deploy to Amazon ECS
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      #   with:
      #     task-definition: task-definition.json
      #     service: testnet-staging-indexer-service
      #     cluster: testnet-staging-cluster
